''' This file declares all the constants being used to send the email
'''
SENDER_EMAIL = "enhancedcwe@gmail.com"
MUO_ACCEPTED_SUBJECT = "Your MUO has been accepted"
ACCEPTED = "accepted"
REVIEWER = "reviewer"
REJECTED = "rejected"
VOTEDUP = "voted up"
VOTEDDOWN = "voted down"
COMMENTED = "comment"
MUO_REJECTED_SUBJECT = "Your MUO has been rejected"
MUO_VOTED_UP_SUBJECT = "Your MUO has been voted up"
MUO_VOTED_DOWN_SUBJECT = "Your MUO has been voted down"
MUO_COMMENTED_SUBJECT = "Your MUO has been commented"
MUO_DUPLICATE_SUBJECT = "Your MUO has been marked as duplicate"
DUPLICATE = "marked as duplicate"
INAPPROPRIATE = "marked as inappropriate"
MUO_INAPPROPRIATE_SUBJECT = "Your MUO has been marked as inappropriate"
MUO_SUBMITTED_FOR_REVIEW_SUBJECT = "Your MUO has been submitted for review"
SUBMITTED = "submitted"
CREATED = "created"
CUSTOM_MUO_CREATED_SUBJECT = "Your Custom MUO has been created"
CUSTOM_MUO_PROMOTED_SUBJECT = "Your Custom MUO has been promoted"
PROMOTED = "promoted"